const allQuestions = [
    // --- Teks Laporan Hasil Observasi (LHO) - Soal 1-25 ---
    { id: 1, text: "Bagian struktur LHO yang berfungsi sebagai pendefinisian, pengklasifikasian, dan penjelasan umum mengenai objek yang diobservasi adalah...", options: ["Deskripsi Bagian", "Pernyataan Umum", "Deskripsi Manfaat", "Tujuan Observasi"], correctAnswer: 1, rationale: "Pernyataan Umum (Definisi Umum) berisi pembukaan, definisi, dan klasifikasi umum mengenai objek.", hint: "Ini adalah bagian pembuka yang memberikan gambaran awal." },
    { id: 2, text: "Dalam LHO, kalimat 'Kopi adalah tanaman perkebunan tahunan yang buahnya dijadikan bahan minuman.' merupakan contoh dari...", options: ["Kalimat Deskripsi", "Kalimat Fakta", "Kalimat Opini", "Kalimat Definisi"], correctAnswer: 3, rationale: "Kalimat Definisi menggunakan verba definitif (seperti: adalah, merupakan, yaitu) untuk menjelaskan arti atau ciri utama suatu objek.", hint: "Fokus pada kata 'adalah'." },
    { id: 3, text: "Kalimat berikut yang merupakan kalimat simpleks adalah...", options: ["Walaupun sakit, Ali tetap datang ke sekolah.", "Ayah membaca koran dan Ibu menyiram bunga.", "Kami pergi ke pasar.", "Karena hujan deras, kami memilih untuk menunda perjalanan."], correctAnswer: 2, rationale: "Kalimat Simpleks (tunggal) hanya mengandung satu klausa (satu subjek dan satu predikat). Opsi A, B, dan D adalah kalimat kompleks.", hint: "Cari kalimat yang paling sederhana, hanya memiliki satu aksi utama." },
    { id: 4, text: "Manakah yang merupakan kaidah kebahasaan verba (kata kerja) material dalam LHO?", options: ["Pohon itu tinggi dan besar.", "Dia seorang peneliti yang teliti.", "Mereka mengamati proses fotosintesis.", "Hasil penelitian itu akurat."], correctAnswer: 2, rationale: "Verba material menunjukkan perbuatan fisik atau peristiwa. 'Mengamati' adalah contoh verba material.", hint: "Cari kata yang menunjukkan adanya kegiatan fisik." },
    { id: 5, text: "Tujuan utama dari Teks Laporan Hasil Observasi adalah...", options: ["Mempengaruhi pembaca agar setuju dengan pendapat penulis.", "Menyajikan hiburan dan sindiran sosial.", "Menyampaikan informasi secara objektif dan sistematis hasil pengamatan.", "Membujuk pembaca untuk membeli suatu produk."], correctAnswer: 2, rationale: "LHO bertujuan memberikan informasi faktual berdasarkan pengamatan tanpa opini pribadi.", hint: "Laporan harus bersifat ilmiah dan berdasarkan fakta." },
    { id: 6, text: "Kalimat 'Pisang Raja memiliki kulit berwarna kuning dengan bintik hitam dan rasanya manis.' berada pada bagian struktur LHO...", options: ["Pernyataan Umum", "Tujuan Observasi", "Deskripsi Bagian", "Simpulan"], correctAnswer: 2, rationale: "Deskripsi Bagian berisi perincian atau ciri-ciri spesifik dari objek yang diobservasi.", hint: "Ini adalah deskripsi rinci tentang ciri-ciri fisik objek." },
    { id: 7, text: "Kata yang termasuk Nomina (Kata Benda) dalam kalimat 'Pengamatan terhadap serangga itu dilakukan secara teliti.' adalah...", options: ["Pengamatan", "terhadap", "dilakukan", "teliti"], correctAnswer: 0, rationale: "Nomina adalah kata yang dapat menduduki fungsi subjek atau objek. 'Pengamatan' adalah kata benda.", hint: "Nomina sering memiliki imbuhan 'pe-' atau 'ke-'." },
    { id: 8, text: "Kalimat kompleks yang tepat untuk menggabungkan dua kalimat 'Peneliti mengambil sampel air. Sampel air itu kemudian diuji di laboratorium.' adalah...", options: ["Peneliti mengambil sampel air, meskipun sampel air itu kemudian diuji di laboratorium.", "Sampel air yang diambil peneliti kemudian diuji di laboratorium.", "Peneliti mengambil sampel air atau sampel air itu kemudian diuji di laboratorium.", "Peneliti mengambil sampel air, tetapi sampel air itu kemudian diuji di laboratorium."], correctAnswer: 1, rationale: "Opsi B adalah kalimat kompleks bertingkat yang efektif, menggabungkan kedua ide tanpa konjungsi yang tidak perlu.", hint: "Kalimat kompleks (majemuk) minimal memiliki dua klausa." },
    { id: 9, text: "Penulisan judul LHO yang benar adalah...", options: ["Pemanfaatan Limbah Plastik Di Lingkungan Sekolah", "Pemanfaatan Limbah Plastik di Lingkungan Sekolah", "Pemanfaatan Limbah plastik di Lingkungan Sekolah", "PEMANFAATAN LIMBAH PLASTIK DI LINGKUNGAN SEKOLAH"], correctAnswer: 1, rationale: "Setiap kata utama (kecuali kata depan/konjungsi, seperti 'di') harus diawali huruf kapital.", hint: "Perhatikan penggunaan huruf kapital pada kata depan." },
    { id: 10, text: "Makna kata 'hibrida' dalam konteks laporan hasil observasi tentang tumbuhan adalah...", options: ["Tumbuhan yang hidup di air.", "Tumbuhan yang tumbuh alami di hutan.", "Tumbuhan hasil perkawinan silang dari dua jenis berbeda.", "Tumbuhan yang berumur pendek."], correctAnswer: 2, rationale: "Hibrida adalah hasil dari persilangan dua varietas yang berbeda untuk mendapatkan sifat unggul.", hint: "Kata ini sering digunakan dalam bidang biologi atau pertanian." },
    { id: 11, text: "Berikut adalah ciri kebahasaan LHO, *kecuali*...", options: ["Menggunakan verba relasional dan material.", "Menggunakan pronomina penunjuk.", "Menggunakan kalimat interogatif dan imperatif.", "Menggunakan Nomina dan frasa nomina."], correctAnswer: 2, rationale: "LHO bersifat objektif dan informatif, sehingga tidak menggunakan kalimat tanya (interogatif) atau kalimat perintah (imperatif).", hint: "LHO tidak boleh memerintah atau bertanya kepada pembaca." },
    { id: 12, text: "Bagian simpulan dalam LHO berisi...", options: ["Pendefinisian objek secara umum.", "Perincian bagian-bagian objek.", "Ringkasan umum mengenai hasil observasi dan manfaatnya.", "Saran kepada pihak terkait."], correctAnswer: 2, rationale: "Simpulan adalah ringkasan akhir yang mengintegrasikan hasil dan manfaat observasi.", hint: "Simpulan adalah penutup yang merangkum keseluruhan isi." },
    { id: 13, text: "Kalimat deskripsi yang paling efektif dalam LHO adalah...", options: ["Bunga mawar adalah tanaman yang indah.", "Mawar merah melambangkan keberanian dan cinta.", "Mawar merah memiliki lima helai kelopak, beraroma kuat, dan batangnya berduri tajam.", "Saya sangat suka melihat bunga mawar itu."], correctAnswer: 2, rationale: "Kalimat deskripsi yang efektif harus menyajikan ciri-ciri fisik yang spesifik dan objektif (jumlah, warna, aroma, ciri khusus).", hint: "Cari kalimat yang paling rinci dan faktual." },
    { id: 14, text: "Urutan yang tepat dalam menyusun LHO adalah...", options: ["Definisi Umum - Deskripsi Manfaat - Deskripsi Bagian.", "Deskripsi Manfaat - Definisi Umum - Deskripsi Bagian.", "Definisi Umum - Deskripsi Bagian - Deskripsi Manfaat.", "Deskripsi Bagian - Definisi Umum - Deskripsi Manfaat."], correctAnswer: 2, rationale: "Struktur LHO adalah Pernyataan Umum (Definisi Umum) diikuti oleh perincian (Deskripsi Bagian) dan diakhiri dengan Simpulan/Manfaat (Deskripsi Manfaat).", hint: "Mulai dari gambaran besar ke detail spesifik." },
    { id: 15, text: "Kata yang mengalami afiksasi (pengimbuhan) prefiks *ber-* yang bermakna memiliki adalah...", options: ["berjalan", "berbicara", "bersepatu", "berkata"], correctAnswer: 2, rationale: "Bersepatu artinya memiliki sepatu. Berjalan, berbicara, dan berkata bermakna melakukan pekerjaan.", hint: "Cari kata yang maknanya dapat diganti dengan 'mempunyai'." },
    { id: 16, text: "Penulisan yang benar dari kata berimbuhan dengan kata dasar 'serta' adalah...", options: ["menyertai", "peserta", "kesertaan", "semua benar"], correctAnswer: 3, rationale: "Semua kata ('menyertai', 'peserta', 'kesertaan') adalah bentukan yang benar dari kata dasar 'serta' dengan berbagai afiksasi.", hint: "Perhatikan kaidah perubahan bunyi/fonem pada afiksasi." },
    { id: 17, text: "Kata 'di' yang berfungsi sebagai imbuhan (verba pasif) yang benar terdapat pada kalimat...", options: ["Surat itu di kirimkan kemarin.", "Di sana ada banyak burung.", "Bunga di tanam di pekarangan.", "Pulpen itu di letakkan di atas meja."], correctAnswer: 2, rationale: "'Ditanam' (di- + tanam) menunjukkan verba pasif dan penulisannya harus digabung. Opsi A, B, D salah karena kata 'di' tidak tepat penulisannya.", hint: "Jika 'di' dapat diganti dengan 'ter-' atau diikuti kata kerja, maka 'di-' harus digabung." },
    { id: 18, text: "Makna 'dilebur' dalam kalimat 'Logam itu dilebur dengan suhu tinggi.' adalah...", options: ["dipanaskan", "dicampur", "dicetak", "dicairkan"], correctAnswer: 3, rationale: "'Dilebur' (dari kata dasar 'lebur') berarti dicairkan (menjadi cair) karena dipanaskan.", hint: "Pikirkan proses apa yang terjadi pada logam saat dipanaskan sangat tinggi." },
    { id: 19, text: "Dalam kaidah kebahasaan LHO, frasa nomina yang berfungsi sebagai penjelas biasanya menggunakan kata penghubung...", options: ["atau", "dan", "yang", "seperti"], correctAnswer: 2, rationale: "Frasa nomina penjelas (misalnya: Harimau *yang* dilindungi) sering menggunakan konjungsi subordinatif 'yang'.", hint: "Kata ini sering menghubungkan kata benda dengan penjelasnya." },
    { id: 20, text: "Kesalahan penulisan kata berimbuhan terdapat pada kalimat...", options: ["Padi mulai menguning.", "Kita harus mensyukuri nikmat Tuhan.", "Ayah memperluas lahan pertaniannya.", "Dia terdiam seribu bahasa."], correctAnswer: 1, rationale: "Kata dasar 'syukur' seharusnya menjadi 'mensyukuri' dengan prefix *meN-* yang melebur menjadi *meny*-, bukan *menS*.", hint: "Cek aturan perubahan fonem pada imbuhan meN-." },
    { id: 21, text: "Kalimat berikut yang mengandung verba relasional (penghubung) adalah...", options: ["Bunga melati beraroma harum.", "Rusa adalah hewan herbivora.", "Pengunjung mengagumi keindahan pantai.", "Mereka berjalan kaki menuju puncak."], correctAnswer: 1, rationale: "Verba relasional (adalah, merupakan, yaitu) menghubungkan subjek dengan pelengkap (klasifikasi/identifikasi).", hint: "Verba ini berfungsi sebagai penjelas atau penyama arti." },
    { id: 22, text: "Kalimat 'Pencemaran udara di kota-kota besar dapat **menyebabkan** berbagai masalah kesehatan.' memiliki fungsi kaidah kebahasaan...", options: ["Verba material", "Verba relasional", "Kata berimbuhan", "Konjungsi kausalitas"], correctAnswer: 3, rationale: "Konjungsi kausalitas (sebab-akibat) ditunjukkan oleh kata kerja 'menyebabkan'.", hint: "Cari kata yang menunjukkan hubungan sebab-akibat." },
    { id: 23, text: "Kalimat kompleks yang mengandung hubungan pertentangan (konjungsi kontras) adalah...", options: ["Dia tetap semangat meskipun gagal berkali-kali.", "Kami makan bersama setelah tugas selesai.", "Karena terlalu lelah, ia tertidur di sofa.", "Dia rajin berolahraga agar tubuhnya sehat."], correctAnswer: 0, rationale: "'Meskipun' adalah konjungsi yang menyatakan hubungan kontras atau pertentangan.", hint: "Cari kata hubung yang berarti 'walaupun' atau 'tetapi'." },
    { id: 24, text: "Penulisan kutipan tidak langsung yang benar adalah...", options: ["Menurut Ali, 'Semua siswa harus rajin belajar'.", "Ali mengatakan bahwa semua siswa harus rajin belajar.", "Ali berkata, Semua siswa harus rajin belajar.", "Ali: 'Semua siswa harus rajin belajar.'"], correctAnswer: 1, rationale: "Kutipan tidak langsung tidak menggunakan tanda kutip dan biasanya diikuti kata penghubung 'bahwa'.", hint: "Kutipan tidak langsung melaporkan kembali ucapan orang lain." },
    { id: 25, text: "Manakah penulisan daftar pustaka dari buku yang benar?", options: ["Gumilar, Sefi Indra dan Fadillah Tri Aulia. 2021. Cerdas Cergas. Jakarta: Pusat Kurikulum dan Perbukuan.", "Aulia, Fadillah Tri, dan Sefi Indra Gumilar. 2021. Cerdas Cergas Berbahasa dan Bersastra Indonesia. Jakarta: Pusat Kurikulum dan Perbukuan.", "Cerdas Cergas Berbahasa dan Bersastra Indonesia. Aulia, Fadillah Tri, dan Sefi Indra Gumilar. Jakarta: Pusat Kurikulum dan Perbukuan. 2021.", "Aulia, F. T. dan S. I. Gumilar. Cerdas Cergas. 2021. Jakarta: Pusat Kurikulum dan Perbukuan."], correctAnswer: 1, rationale: "Urutan yang benar: Nama Penulis (dibalik untuk nama pertama), Tahun Terbit, Judul Buku (dicetak miring), Kota Terbit, dan Nama Penerbit.", hint: "Perhatikan urutan: Nama (dibalik) - Tahun - Judul (Miring) - Kota - Penerbit." },

    // --- Teks Anekdot - Soal 26-50 ---
    { id: 26, text: "Teks yang berisi cerita singkat yang lucu dan mengesankan, yang biasanya bertujuan menyampaikan kritik atau sindiran terhadap tokoh publik atau kebijakan tertentu, disebut...", options: ["Teks Hikayat", "Teks Fabel", "Teks Anekdot", "Teks Humor"], correctAnswer: 2, rationale: "Anekdot adalah cerita lucu pendek yang mengandung kritik/sindiran penting.", hint: "Teks ini bersifat lucu dan mengandung 'pesan tersembunyi'." },
    { id: 27, text: "Bagian awal anekdot yang berisi pengenalan situasi atau latar belakang cerita adalah...", options: ["Abstraksi", "Reaksi", "Krisis", "Koda"], correctAnswer: 0, rationale: "Abstraksi adalah bagian pembuka yang memberikan gambaran umum tentang isi teks.", hint: "Abstraksi adalah pengantar atau ringkasan awal." },
    { id: 28, text: "Bagian anekdot yang memuat masalah utama yang akan disindir atau dikritik adalah...", options: ["Abstraksi", "Orientasi", "Krisis", "Reaksi"], correctAnswer: 2, rationale: "Krisis adalah bagian inti anekdot, di mana muncul masalah yang memicu kelucuan sekaligus kritikan.", hint: "Ini adalah saat konflik mencapai puncaknya." },
    { id: 29, text: "Kalimat berikut yang menunjukkan konjungsi waktu (kaidah kebahasaan anekdot) adalah...", options: ["Saya bingung dan sedih.", "Tiba-tiba, lampu di ruangan itu padam.", "Dia sangat pintar, tetapi malas.", "Mereka tertawa terbahak-bahak."], correctAnswer: 1, rationale: "'Tiba-tiba' adalah konjungsi waktu yang sering digunakan untuk menunjukkan perubahan atau kejadian mendadak.", hint: "Cari kata yang berhubungan dengan urutan atau waktu kejadian." },
    { id: 30, text: "Langkah penyusunan anekdot yang tepat setelah menentukan topik adalah...", options: ["Menyusun Koda", "Menentukan Tujuan Sindiran", "Menentukan Abstraksi", "Menyusun Krisis"], correctAnswer: 1, rationale: "Setelah topik (inti masalah), penulis harus menentukan tokoh/objek yang akan disindir (tujuan) sebelum mengembangkan strukturnya.", hint: "Anekdot harus memiliki target kritik yang jelas." },
    { id: 31, text: "Teks Anekdot haruslah memiliki unsur kejutan atau kelucuan (humor) pada bagian...", options: ["Orientasi dan Koda", "Krisis dan Reaksi", "Abstraksi dan Orientasi", "Krisis dan Koda"], correctAnswer: 1, rationale: "Kelucuan atau sindiran utama muncul saat Krisis, yang kemudian direspons oleh tokoh pada bagian Reaksi.", hint: "Puncak masalah dan respons terhadap masalah adalah kunci kelucuan." },
    { id: 32, text: "Berikut adalah ciri kebahasaan Teks Anekdot, *kecuali*...", options: ["Menggunakan kata kerja aksi/material.", "Menggunakan kalimat retoris.", "Menggunakan majas perbandingan yang dominan.", "Menggunakan keterangan waktu lampau."], correctAnswer: 2, rationale: "Meskipun majas bisa ada, anekdot tidak didominasi oleh majas perbandingan (metafora, simile), melainkan kaidah kebahasaan naratif dan sindiran.", hint: "Fokus utama anekdot ada pada urutan kejadian dan kritik." },
    { id: 33, text: "Kalimat retoris adalah...", options: ["Kalimat yang membutuhkan jawaban cepat.", "Kalimat tanya yang tidak membutuhkan jawaban.", "Kalimat yang menggunakan kata kerja aktif.", "Kalimat yang berisi perintah."], correctAnswer: 1, rationale: "Kalimat retoris adalah pertanyaan yang diajukan untuk memberikan penekanan atau sindiran, bukan untuk dijawab.", hint: "Pertanyaan yang tujuannya bukan untuk mendapatkan informasi." },
    { id: 34, text: "Bagian Koda dalam Teks Anekdot berfungsi sebagai...", options: ["Puncak konflik cerita.", "Penutup atau simpulan.", "Pengenalan tokoh.", "Respons terhadap masalah."], correctAnswer: 1, rationale: "Koda adalah bagian penutup yang seringkali berisi simpulan atau penegasan kembali kelucuan/sindiran.", hint: "Koda seperti epilog atau akhir cerita." },
    { id: 35, text: "Kalimat yang menunjukkan keterangan waktu lampau adalah...", options: ["Saat ini kami sedang belajar.", "Minggu depan dia akan pergi.", "Pada suatu hari, sang raja marah besar.", "Mereka selalu bekerja keras."], correctAnswer: 2, rationale: "'Pada suatu hari' menunjukkan waktu yang telah lewat atau lampau, khas digunakan dalam cerita.", hint: "Cari frasa yang menunjukkan kejadian di masa lalu." },
    { id: 36, text: "Teks Anekdot berbeda dengan Hikayat karena...", options: ["Anekdot bersifat fiktif, Hikayat bersifat nyata.", "Anekdot bertujuan menghibur, Hikayat bertujuan mendidik.", "Anekdot bersifat modern, Hikayat bersifat klasik.", "Anekdot mengandung kritik, Hikayat mengandung nilai luhur."], correctAnswer: 2, rationale: "Anekdot (modern) adalah karya sastra baru, sementara Hikayat (klasik) adalah sastra lama Melayu.", hint: "Perhatikan perbedaan masa munculnya kedua jenis teks." },
    { id: 37, text: "Sindiran yang paling mungkin terdapat dalam anekdot tentang seorang pejabat yang sering terlambat rapat adalah...", options: ["Pejabat itu sangat sibuk.", "Pejabat itu tidak menghargai waktu.", "Rapat itu tidak penting.", "Semua pejabat memang suka terlambat."], correctAnswer: 1, rationale: "Kritik/sindiran dalam anekdot berfokus pada masalah etika atau kebijakan tokoh yang disindir, yaitu ketidakdisiplinan.", hint: "Fokus pada apa yang seharusnya dilakukan oleh pejabat tersebut." },
    { id: 38, text: "Urutan struktur anekdot yang benar adalah...", options: ["Abstraksi - Krisis - Orientasi - Reaksi - Koda.", "Abstraksi - Orientasi - Krisis - Reaksi - Koda.", "Orientasi - Abstraksi - Krisis - Reaksi - Koda.", "Krisis - Orientasi - Abstraksi - Reaksi - Koda."], correctAnswer: 1, rationale: "Urutan struktur yang baku adalah Abstraksi (pembuka), Orientasi (latar), Krisis (konflik), Reaksi (respons), dan Koda (penutup).", hint: "Ingatlah singkatan A-O-K-R-K." },
    { id: 39, text: "Bagian Orientasi pada anekdot berfungsi untuk...", options: ["Menyelesaikan masalah.", "Menyajikan ringkasan cerita.", "Memperkenalkan tokoh, latar, dan waktu.", "Menunjukkan puncak konflik."], correctAnswer: 2, rationale: "Orientasi adalah tahap pembangunan cerita, memperkenalkan siapa, di mana, dan kapan cerita terjadi.", hint: "Ini adalah fondasi cerita." },
    { id: 40, text: "Kalimat berikut yang mengandung kata kerja aksi/material adalah...", options: ["Dia adalah seorang guru.", "Buku itu di atas meja.", "Anak-anak berlari di lapangan.", "Langit terlihat mendung."], correctAnswer: 2, rationale: "'Berlari' adalah kata kerja yang menunjukkan tindakan fisik yang dilakukan oleh subjek.", hint: "Cari kata yang menunjukkan subjek sedang melakukan sesuatu." },
    { id: 41, text: "Makna tersirat dari anekdot yang menceritakan seorang pengemis yang menolak uang receh karena 'uangnya harus yang baru' adalah...", options: ["Pengemis itu sombong.", "Pengemis itu benar-benar miskin.", "Sindiran terhadap kondisi mata uang yang kotor/rusak.", "Sindiran terhadap standar hidup yang tinggi di kalangan bawah."], correctAnswer: 3, rationale: "Sindiran sering ditujukan pada fenomena sosial yang ironis, di mana orang yang seharusnya menerima apa saja malah memiliki standar yang tidak masuk akal.", hint: "Cari ironi atau kritik sosial yang tersembunyi." },
    { id: 42, text: "Tujuan utama penggunaan Kalimat Retoris dalam Teks Anekdot adalah...", options: ["Meminta konfirmasi dari pembaca.", "Membantu pembaca memahami alur cerita.", "Memperkuat sindiran atau kritik.", "Menunjukkan emosi tokoh secara berlebihan."], correctAnswer: 2, rationale: "Kalimat retoris digunakan untuk penekanan, yang dalam anekdot berfungsi untuk mempertajam kritik atau sindiran.", hint: "Retoris = Penekanan Kritik." },
    { id: 43, text: "Berikut adalah kata kerja yang menunjukkan makna lampau, *kecuali*...", options: ["pernah", "sudah", "kemarin", "nanti"], correctAnswer: 3, rationale: "'Nanti' menunjukkan waktu yang akan datang (futuristik), bukan waktu lampau.", hint: "Cari kata yang menunjukkan waktu yang akan terjadi." },
    { id: 44, text: "Manakah yang merupakan contoh kritik terhadap kebijakan publik?", options: ["Mahasiswa itu mengkritik temannya yang malas.", "Warga mengkritik kurangnya lampu penerangan jalan di lingkungan mereka.", "Anak itu mengkritik masakan ibunya yang kurang asin.", "Pengemis mengkritik tukang parkir yang tidak jujur."], correctAnswer: 1, rationale: "Kebijakan publik (pemerintah daerah/negara) mencakup fasilitas umum seperti penerangan jalan.", hint: "Fokus pada masalah yang menjadi tanggung jawab pemerintah/lembaga publik." },
    { id: 45, text: "Kalimat 'Apakah kamu tahu betapa pentingnya kejujuran di era sekarang?' dalam anekdot berfungsi sebagai...", options: ["Orientasi", "Reaksi", "Krisis", "Koda/Sindiran"], correctAnswer: 3, rationale: "Jika diletakkan di akhir, pertanyaan retoris ini berfungsi sebagai penutup yang menguatkan sindiran tentang kejujuran (Koda/Sindiran).", hint: "Ini adalah pertanyaan yang memicu pemikiran, bukan alur." },
    { id: 46, text: "Kata kerja yang menunjukkan aksi mental adalah...", options: ["menggambar", "menulis", "merasakan", "memukul"], correctAnswer: 2, rationale: "Kata kerja aksi mental melibatkan perasaan atau pikiran, seperti 'merasakan', 'mengetahui', 'memikirkan'.", hint: "Aksi mental = proses di dalam pikiran/perasaan." },
    { id: 47, text: "Apa yang membedakan Teks Anekdot fiktif dan nonfiktif?", options: ["Anekdot nonfiktif selalu lucu, fiktif tidak.", "Anekdot fiktif tidak mengandung kritik, nonfiktif mengandung kritik.", "Anekdot nonfiktif berdasarkan kejadian nyata, fiktif berdasarkan rekaan.", "Anekdot fiktif lebih pendek dari nonfiktif."], correctAnswer: 2, rationale: "Perbedaan utama fiktif dan nonfiktif terletak pada basis ceritanya: nyata atau rekaan.", hint: "Fiktif = karangan, Nonfiktif = fakta." },
    { id: 48, text: "Sindiran halus yang efektif dalam anekdot disebut juga...", options: ["Ironi", "Sarkasme", "Hiperbola", "Litotes"], correctAnswer: 0, rationale: "Ironi adalah majas sindiran halus atau menggunakan kata yang bertentangan dengan maksud sebenarnya.", hint: "Sindiran yang bersifat 'manis' di permukaan, tetapi tajam di dalam." },
    { id: 49, text: "Kalimat berikut yang paling tepat untuk mengisi bagian Reaksi setelah Krisis (masalah) adalah...", options: ["Akhirnya, masalah itu selesai.", "Dia hanya bisa tersenyum dan menggelengkan kepala.", "Mereka memutuskan untuk pergi besok.", "Pemerintah segera merespons kritik tersebut."], correctAnswer: 1, rationale: "Reaksi dalam anekdot biasanya berupa respons singkat, lucu, atau menyindir dari tokoh terhadap krisis.", hint: "Cari respons yang menunjukkan kelucuan atau kepasrahan." },
    { id: 50, text: "Jika anekdot menyindir kebiasaan buruk masyarakat, tujuan sindiran itu adalah...", options: ["Menghibur pembaca.", "Mendapatkan popularitas.", "Mengubah kebiasaan buruk tersebut secara persuasif.", "Mengecam tanpa solusi."], correctAnswer: 2, rationale: "Meskipun lucu, tujuan utama kritik adalah untuk memberikan kesadaran dan mendorong perubahan yang lebih baik (persuasif).", hint: "Tujuan kritik yang baik adalah perbaikan." },

    // --- Hikayat - Soal 51-75 ---
    { id: 51, text: "Hikayat merupakan salah satu jenis karya sastra lama yang ditulis dalam bahasa...", options: ["Sunda", "Jawa Kuno", "Melayu Klasik", "Sanskerta"], correctAnswer: 2, rationale: "Hikayat termasuk dalam khazanah sastra Melayu Klasik.", hint: "Sastra lama di wilayah Nusantara Barat." },
    { id: 52, text: "Ciri khas hikayat yang berarti cerita tidak diketahui secara jelas nama pengarangnya adalah...", options: ["Istanasentris", "Anonim", "Kemustahilan", "Arkais"], correctAnswer: 1, rationale: "Anonim berarti tidak diketahui nama pengarangnya, karena hikayat diturunkan secara lisan.", hint: "Fokus pada siapa penulisnya." },
    { id: 53, text: "Unsur kemustahilan dalam hikayat ditunjukkan oleh...", options: ["Cerita berlatar istana.", "Penggunaan bahasa Melayu lama.", "Tokoh utama memiliki kesaktian luar biasa.", "Menceritakan tentang raja dan ratu."], correctAnswer: 2, rationale: "Kesaktian yang luar biasa, seperti dapat terbang atau mengubah wujud, adalah contoh kemustahilan yang melanggar logika.", hint: "Cari hal yang tidak mungkin terjadi di dunia nyata." },
    { id: 54, text: "Berikut adalah salah satu fungsi hikayat, *kecuali*...", options: ["Sarana hiburan.", "Sarana pendidikan moral.", "Media kritik sosial.", "Pelestarian budaya."], correctAnswer: 2, rationale: "Kritik sosial adalah fungsi utama Anekdot. Hikayat berfungsi sebagai hiburan, pendidikan, dan warisan budaya.", hint: "Kritik sosial adalah ciri teks yang lebih modern." },
    { id: 55, text: "Nilai yang terkandung dalam hikayat yang berhubungan dengan kepercayaan atau ritual keagamaan disebut nilai...", options: ["Moral", "Sosial", "Budaya", "Agama"], correctAnswer: 3, rationale: "Nilai Agama berhubungan dengan keyakinan, ajaran, dan ritual Ketuhanan.", hint: "Fokus pada aspek spiritual dan keimanan." },
    { id: 56, text: "Latar hikayat yang dominan menceritakan kehidupan istana, raja, dan bangsawan disebut...", options: ["Istanasentris", "Feodalisme", "Kemustahilan", "Anonim"], correctAnswer: 0, rationale: "Istanasentris berarti pusat ceritanya adalah kehidupan istana.", hint: "Fokus pada latar tempat dan tokoh utama." },
    { id: 57, text: "Makna kata arkais 'hatta' yang lazim ditemukan dalam hikayat adalah...", options: ["Maka", "Kemudian", "Alkisah", "Konon"], correctAnswer: 1, rationale: "Hatta berarti 'kemudian' dan sering digunakan sebagai penghubung waktu atau peristiwa.", hint: "Kata ini menandai perpindahan adegan atau waktu." },
    { id: 58, text: "Tokoh yang diceritakan memiliki kesaktian dalam hikayat seringkali adalah...", options: ["Rakyat biasa", "Pedagang kaya", "Penyihir jahat", "Tokoh utama (raja/pangeran)"], correctAnswer: 3, rationale: "Kesaktian adalah atribut yang melekat pada tokoh utama atau pahlawan (raja, pangeran, kesatria) untuk menunjukkan keagungannya.", hint: "Tokoh protagonis seringkali yang paling sakti." },
    { id: 59, text: "Perbedaan utama Hikayat dan Cerpen adalah...", options: ["Hikayat memiliki alur yang lebih rumit, Cerpen lebih sederhana.", "Hikayat bersifat anonim, Cerpen diketahui penulisnya.", "Hikayat menggunakan sudut pandang orang pertama, Cerpen orang ketiga.", "Hikayat selalu berakhir bahagia, Cerpen tidak."], correctAnswer: 1, rationale: "Anonimitas adalah ciri pembeda utama sastra lama (Hikayat) dari sastra modern (Cerpen).", hint: "Siapa yang menulis adalah kuncinya." },
    { id: 60, text: "Kutipan: 'Maka baginda pun bimbanglah, tidak tahu siapa yang patut dirayakan dalam negeri karena anaknya kedua orang itu sama-sama gagah.' Nilai yang terkandung adalah...", options: ["Nilai sosial", "Nilai budaya", "Nilai moral", "Nilai agama"], correctAnswer: 1, rationale: "Pewarisan takhta atau penentuan pengganti raja adalah bagian dari tradisi/adat istana, yang mencerminkan Nilai Budaya.", hint: "Fokus pada tradisi atau adat istiadat kerajaan." },
    { id: 61, text: "Makna kata arkais 'alkisah' adalah...", options: ["Cerita bermula", "Akhirnya", "Kemudian", "Sungguh"], correctAnswer: 0, rationale: "Alkisah sering digunakan sebagai penanda awal cerita, yang berarti 'Permulaan cerita' atau 'Cerita bermula'.", hint: "Kata ini sering ditemukan di awal-awal hikayat." },
    { id: 62, text: "Gaya bahasa hikayat yang cenderung statis, klise, dan berulang disebut...", options: ["Puitis", "Arkaistik", "Konvensional", "Menggunakan kata penghubung"], correctAnswer: 2, rationale: "Gaya bahasa konvensional berarti menggunakan pola yang sudah mapan, klise, dan diwariskan dari generasi ke generasi.", hint: "Gaya bahasa yang tidak banyak berubah." },
    { id: 63, text: "Nilai yang mengajarkan tentang perilaku baik dan buruk, benar dan salah dalam kehidupan manusia adalah nilai...", options: ["Moral", "Sosial", "Budaya", "Pendidikan"], correctAnswer: 0, rationale: "Nilai Moral berkaitan langsung dengan etika, akhlak, dan budi pekerti manusia.", hint: "Fokus pada etika dan perilaku pribadi." },
    { id: 64, text: "Sifat tokoh dalam hikayat yang tidak diketahui latar belakangnya secara rinci dan cenderung hitam-putih (baik mutlak atau jahat mutlak) disebut...", options: ["Penokohan dinamis", "Penokohan flat", "Penokohan kompleks", "Penokohan protagonis"], correctAnswer: 1, rationale: "Tokoh flat (datar) adalah tokoh yang sifatnya tidak berubah dan sederhana (baik atau jahat saja).", hint: "Karakter yang sederhana dan tidak berkembang." },
    { id: 65, text: "Penggunaan sudut pandang dalam hikayat yang paling dominan adalah...", options: ["Orang pertama 'Aku'", "Orang pertama 'Kami'", "Orang ketiga 'Dia' (serba tahu)", "Orang ketiga 'Dia' (terbatas)"], correctAnswer: 2, rationale: "Sifat Anonim dan Istanasentris membuat narator memiliki kuasa penuh atas cerita (serba tahu).", hint: "Narator mengetahui semua hal yang terjadi pada tokoh." },
    { id: 66, text: "Hikayat berfungsi sebagai 'Sarana Pendidikan' karena...", options: ["Menceritakan kisah orang-orang cerdas.", "Mengandung banyak ilmu pengetahuan umum.", "Di dalamnya terdapat nilai-nilai yang dapat diteladani.", "Menggunakan bahasa yang sulit dipahami."], correctAnswer: 2, rationale: "Nilai-nilai luhur seperti moral, agama, dan kepahlawanan adalah inti dari fungsi pendidikan hikayat.", hint: "Fokus pada pesan yang disampaikan." },
    { id: 67, text: "Kalimat yang menunjukkan kemustahilan dalam hikayat adalah...", options: ["Pangeran itu pergi berburu ke hutan.", "Bayi itu lahir disertai sebilah pedang.", "Raja dan Ratu sangat menyayangi putranya.", "Patih itu setia kepada rajanya."], correctAnswer: 1, rationale: "Kelahiran yang disertai benda pusaka adalah hal yang tidak logis dan melanggar nalar.", hint: "Cari elemen yang tidak mungkin terjadi secara realistis." },
    { id: 68, text: "Kata arkais 'upacara' dalam konteks hikayat berarti...", options: ["Benda pusaka", "Harta karun", "Hadiah", "Pesta atau perayaan"], correctAnswer: 3, rationale: "Upacara berarti pesta, perayaan, atau seremoni besar (seperti pernikahan atau penobatan).", hint: "Kata yang berhubungan dengan acara besar kerajaan." },
    { id: 69, text: "Tokoh utama hikayat seringkali dikaitkan dengan...", options: ["Kehidupan rakyat biasa.", "Keluarga kerajaan atau bangsawan.", "Petualangan di lautan.", "Konflik politik modern."], correctAnswer: 1, rationale: "Ciri Istanasentris membuat tokoh utamanya adalah raja, ratu, pangeran, atau bangsawan.", hint: "Fokus pada latar dan tokoh sentral." },
    { id: 70, text: "Ciri 'Kesaktian Tokoh' dalam hikayat seringkali berfungsi untuk...", options: ["Menunjukkan kelemahan tokoh.", "Menciptakan konflik yang realistis.", "Menguatkan unsur kemustahilan dan keagungan tokoh.", "Menghilangkan alur cerita."], correctAnswer: 2, rationale: "Kesaktian menunjukkan kehebatan tokoh yang luar biasa, sehingga menguatkan sifat kemustahilan dan keagungan hikayat.", hint: "Tujuannya untuk menunjukkan keistimewaan tokoh." },
    { id: 71, text: "Bacalah kutipan: 'Adapun akan Tuan Puteri itu terlalu elok parasnya, tiada yang sama di dunia ini.' Kata 'Adapun' berfungsi sebagai...", options: ["Penyelesaian masalah.", "Kata keterangan waktu.", "Penanda dimulainya kalimat baru/perhatian.", "Penutup cerita."], correctAnswer: 2, rationale: "'Adapun' adalah kata arkais yang berfungsi untuk memulai kalimat baru atau mengalihkan perhatian ke tokoh/subjek baru.", hint: "Kata ini sering digunakan di awal kalimat." },
    { id: 72, text: "Nilai yang berkaitan dengan interaksi, hubungan, dan kepatuhan terhadap norma-norma di masyarakat disebut nilai...", options: ["Moral", "Sosial", "Budaya", "Pendidikan"], correctAnswer: 1, rationale: "Nilai Sosial mengatur hubungan antarmanusia dan peran individu dalam komunitas.", hint: "Fokus pada hubungan antarwarga negara/masyarakat." },
    { id: 73, text: "Manakah yang merupakan majas melebih-lebihkan?", options: ["Hiperbola", "Ironi", "Retoris", "Koda"], correctAnswer: 0, rationale: "Hiperbola (melebih-lebihkan) adalah majas yang sering digunakan dalam hikayat untuk menggambarkan keindahan atau kesaktian tokoh secara berlebihan.", hint: "Cari majas yang membuat sesuatu terlihat lebih besar/hebat dari kenyataan." },
    { id: 74, text: "Peristiwa penting dalam hikayat yang sering terjadi setelah tokoh utama mendapat cobaan besar adalah...", options: ["Tokoh utama meninggal.", "Tokoh utama kembali ke kehidupan biasa.", "Tokoh utama mendapat kesaktian atau bantuan ajaib.", "Hikayat berakhir dengan sedih."], correctAnswer: 2, rationale: "Dalam hikayat, cobaan seringkali menjadi ujian yang mengarah pada anugerah kesaktian atau bantuan supernatural.", hint: "Karakteristik penceritaan heroik/fantastis." },
    { id: 75, text: "Kata arkais yang memiliki arti 'Maka' adalah...", options: ["Syahdan", "Maka", "Hatta", "Alkisah"], correctAnswer: 1, rationale: "Kata 'Maka' itu sendiri adalah kata arkais yang sering digunakan sebagai konjungsi atau penanda awal kalimat dalam hikayat.", hint: "Kata penghubung yang paling umum di hikayat." },

    // --- Kaidah Bahasa & Penulisan - Soal 76-109 ---
    { id: 76, text: "Penulisan afiksasi yang benar dari kata dasar 'salah' dengan prefiks *ke-* dan sufiks *-an* adalah...", options: ["kesalahan", "kesalahan", "kesalahan", "kesalahan"], correctAnswer: 0, rationale: "Bentukan kata benda yang benar dari 'salah' adalah 'kesalahan'.", hint: "Perhatikan kaidah penulisan huruf kapital." },
    { id: 77, text: "Kata depan yang benar dalam kalimat 'Dia berjalan ... toko buku.' adalah...", options: ["ketoko", "ke toko", "ke-toko", "ketoko buku"], correctAnswer: 1, rationale: "Kata depan 'ke' (menunjukkan tempat) harus ditulis terpisah dari kata yang mengikutinya.", hint: "Kata depan dipisah, imbuhan digabung." },
    { id: 78, text: "Manakah penulisan kata 'di' sebagai kata depan yang benar?", options: ["Disana", "Dibawah", "Di atas", "Diperoleh"], correctAnswer: 2, rationale: "'Di atas' menunjukkan tempat dan harus dipisah. 'Disana' (seharusnya 'di sana'), 'Dibawah' (seharusnya 'di bawah'), dan 'Diperoleh' (imbuhan, harus digabung) salah.", hint: "Kata 'di' yang menunjukkan tempat harus dipisah." },
    { id: 79, text: "Kalimat yang menggunakan majas Hiperbola (melebih-lebihkan) adalah...", options: ["Wajahnya cantik seperti bidadari.", "Suara merdunya memecahkan gendang telinga.", "Dia adalah pahlawan tanpa tanda jasa.", "Penjahat itu tertangkap basah."], correctAnswer: 1, rationale: "Memecahkan gendang telinga adalah pernyataan yang sangat berlebihan untuk menggambarkan suara yang sangat keras.", hint: "Cari pernyataan yang tidak mungkin secara logis." },
    { id: 80, text: "Majas yang memberikan sifat-sifat manusia kepada benda mati adalah...", options: ["Metafora", "Personifikasi", "Litotes", "Ironi"], correctAnswer: 1, rationale: "Personifikasi (dari kata 'persona' = orang) membuat benda mati/tidak hidup seolah-olah bernyawa dan berperilaku seperti manusia.", hint: "Contoh: Angin *berbisik*." },
    { id: 81, text: "Penulisan kutipan langsung yang benar adalah...", options: ["Dia berkata bahwa, 'Saya akan datang besok'.", "Ayah menasihati: Jujur adalah kunci sukses.", "Guru bertanya, 'Siapa yang sudah menyelesaikan tugas?'", "Saya bertanya, apakah kamu sudah makan?"], correctAnswer: 2, rationale: "Kutipan langsung diapit tanda kutip ('...'), didahului koma, dan diikuti dengan kalimat pengantar.", hint: "Kutipan langsung harus persis seperti ucapan aslinya." },
    { id: 82, text: "Kata 'di' yang berfungsi sebagai imbuhan (verba pasif) yang salah penulisannya adalah...", options: ["diambil", "ditulis", "di beli", "dicari"], correctAnswer: 2, rationale: "'Di beli' seharusnya digabung menjadi 'dibeli' karena berfungsi sebagai imbuhan pasif.", hint: "Ingat: Jika bisa diganti 'ter-', maka 'di-' harus digabung." },
    { id: 83, text: "Penulisan daftar pustaka dari artikel jurnal yang benar adalah...", options: ["(2022). Aulia, F. T. Peran Anekdot dalam Kritik Sosial. Jurnal Bahasa. 1(1): 10-20.", "Aulia, F. T. (2022). Peran Anekdot dalam Kritik Sosial. Jurnal Bahasa, 1(1), 10-20.", "Peran Anekdot dalam Kritik Sosial. Aulia, F. T. (2022). Jurnal Bahasa. 1(1): 10-20.", "Aulia, F. T. Peran Anekdot dalam Kritik Sosial. Jurnal Bahasa. 2022. 1(1): 10-20."], correctAnswer: 1, rationale: "Urutan yang benar: Nama penulis (dibalik), (Tahun). Judul artikel (tidak miring). *Nama Jurnal* (miring), Volume(Nomor), Halaman.", hint: "Perhatikan tata letak tanda baca dan cetak miring." },
    { id: 84, text: "Afiksasi yang mengubah kata kerja menjadi kata benda adalah...", options: ["meN-", "di-", "ter-", "peN-an"], correctAnswer: 3, rationale: "PeN-an adalah afiksasi pembentuk nomina (kata benda) dari verba (kata kerja), contoh: *pe*n*tulis*an.", hint: "Cari imbuhan yang menghasilkan kata benda." },
    { id: 85, text: "Kalimat yang menggunakan kata kerja (verba) yang memiliki makna lampau adalah...", options: ["Dia sedang belajar.", "Mereka telah menyelesaikan tugas.", "Kami akan berlibur besok.", "Rusa berlari kencang."], correctAnswer: 1, rationale: "'Telah' menunjukkan bahwa aksi (menyelesaikan) sudah terjadi di masa lampau.", hint: "Cari kata keterangan waktu yang sudah terjadi." },
    { id: 86, text: "Kata 'serta' yang benar dalam kalimat berikut adalah...", options: ["Dia serta dalam rapat itu.", "Dia turut serta dalam rapat itu.", "Dia mensertakan bukti.", "Dia beserta saya pergi ke pasar."], correctAnswer: 1, rationale: "Dalam konteks ini, 'turut serta' lebih lazim dan tepat. 'Mensertakan' harusnya 'menyertakan'.", hint: "Perhatikan kaidah kebahasaan yang paling baku." },
    { id: 87, text: "Majas yang membandingkan dua hal yang berbeda secara langsung tanpa kata penghubung (seperti, bagai) adalah...", options: ["Simile", "Metafora", "Personifikasi", "Hiperbola"], correctAnswer: 1, rationale: "Metafora adalah perbandingan implisit (langsung), contoh: 'Dia adalah *singa* lapangan hijau'.", hint: "Perbandingan yang bersifat kiasan." },
    { id: 88, text: "Kalimat Simpleks dapat diperluas menjadi Kalimat Kompleks dengan penambahan...", options: ["Satu subjek baru.", "Satu predikat baru.", "Satu klausa independen atau dependen baru.", "Satu objek baru."], correctAnswer: 2, rationale: "Kalimat Kompleks (majemuk) terdiri dari minimal dua klausa (klausa independen + dependen/independen).", hint: "Fokus pada struktur klausa." },
    { id: 89, text: "Kalimat berikut yang merupakan Kalimat Definisi adalah...", options: ["Harimau adalah hewan buas.", "Harimau memiliki taring yang tajam.", "Harimau berburu pada malam hari.", "Harimau sedang mencari mangsa."], correctAnswer: 0, rationale: "Kalimat definisi menggunakan 'adalah' untuk mengklasifikasikan atau mendefinisikan subjek.", hint: "Definisi = Menggunakan 'adalah', 'merupakan', atau 'yaitu'." },
    { id: 90, text: "Kaidah kebahasaan anekdot yang menunjukkan hubungan sebab-akibat (kausalitas) adalah...", options: ["sebelum", "karena", "dan", "seperti"], correctAnswer: 1, rationale: "'Karena' adalah konjungsi kausalitas yang menjelaskan alasan atau sebab suatu peristiwa.", hint: "Kata yang menjawab pertanyaan 'mengapa'." },
    { id: 91, text: "Penulisan frasa nomina yang tepat adalah...", options: ["Buku-buku baru", "Baru buku-buku", "Buku baru-baru", "Buku barunya"], correctAnswer: 0, rationale: "Frasa nomina yang tepat adalah *inti* (nomina) diikuti oleh *penjelas* (adjektiva).", hint: "Pola: Kata benda + kata sifat." },
    { id: 92, text: "Imbuhan *meN-* pada kata 'menanam' berubah menjadi *men-* karena kata dasarnya berawal dari huruf...", options: ["k, t, s, p", "t", "n", "m"], correctAnswer: 1, rationale: "Imbuhan *meN-* akan luluh menjadi *men-* jika kata dasarnya diawali huruf *t* (contoh: *tanam* menjadi *menanam*).", hint: "Pikirkan kata 'tulis' menjadi 'menulis'." },
    { id: 93, text: "Tanda baca yang paling sering digunakan dalam penulisan kutipan langsung adalah...", options: ["Tanda kurung ( )", "Tanda titik dua (:)", "Tanda koma (,)", "Tanda kutip ganda ('')"], correctAnswer: 3, rationale: "Tanda kutip ganda ('...') digunakan untuk mengapit ucapan langsung dari tokoh.", hint: "Fokus pada apa yang diucapkan secara persis." },
    { id: 94, text: "Penulisan kutipan tidak langsung dari kalimat 'Saya akan berangkat besok pagi.' (oleh Budi) adalah...", options: ["Budi berkata bahwa dia akan berangkat besok pagi.", "Budi berkata, 'Dia akan berangkat besok pagi.'", "Budi mengatakan bahwa, saya akan berangkat besok pagi.", "Budi berkata bahwa dia akan berangkat hari ini."], correctAnswer: 0, rationale: "Kutipan tidak langsung harus mengubah pronomina dan keterangan waktu agar sesuai dengan konteks pelaporan.", hint: "Ubah 'Saya' menjadi 'dia' dan 'besok' menjadi 'keesokan harinya' (atau biarkan jika konteksnya jelas)." },
    { id: 95, text: "Kalimat 'Mawar adalah bunga yang indah dan beraroma harum.' mengandung klausa sebanyak...", options: ["Satu", "Dua", "Tiga", "Empat"], correctAnswer: 1, rationale: "Kalimat ini adalah Kalimat Kompleks: Klausa 1: 'Mawar adalah bunga yang indah' (Klausa Utama). Klausa 2: 'dan beraroma harum' (Klausa setara).", hint: "Kalimat ini memiliki dua predikat utama yang dihubungkan konjungsi." },
    { id: 96, text: "Penulisan daftar pustaka dari buku 'Menulis Efektif' oleh Siska Sari, terbit di Bandung tahun 2020 oleh Penerbit Abadi adalah...", options: ["Siska Sari. 2020. Menulis Efektif. Bandung: Penerbit Abadi.", "Sari, Siska. 2020. *Menulis Efektif*. Bandung: Penerbit Abadi.", "Sari, Siska. *Menulis Efektif*. 2020. Penerbit Abadi: Bandung.", "Sari, S. (2020). Menulis Efektif. Bandung: Abadi."], correctAnswer: 1, rationale: "Urutan yang benar: Nama penulis (dibalik), Tahun. Judul Buku (dicetak miring). Kota Terbit: Penerbit.", hint: "Judul buku harus dicetak miring." },
    { id: 97, text: "Makna kata arkais 'syahdan' yang lazim ditemukan dalam hikayat adalah...", options: ["Maka", "Konon", "Sesungguhnya", "Alkisah"], correctAnswer: 2, rationale: "Syahdan memiliki arti 'Sesungguhnya' atau 'Adapun' dan merupakan salah satu penanda transisi waktu atau peristiwa dalam hikayat.", hint: "Kata ini sering digunakan untuk memulai kalimat baru atau mengalihkan cerita." },

    // --- Soal ID 98 (EDITED: Opsi Jawaban 3 diubah dari 'Nilai pendidikan' menjadi 'Nilai sosial') ---
    { id: 98, text: "Dalam Hikayat Indera Bangsawan, dikisahkan Indera Bangsawan mengalahkan Buraksa untuk membebaskan Putri Kemala Sari dan rakyat yang ditawan. Nilai yang menonjol dari tindakan Indera Bangsawan tersebut adalah...", 
        options: [
            "Nilai moral", 
            "Nilai budaya", 
            "Nilai sosial", // Opsi ini diubah/ditegaskan
            "Nilai agama"
        ], 
        correctAnswer: 2, 
        rationale: "Tindakan menyelamatkan masyarakat dari penindasan Buraksa merupakan tindakan yang berorientasi pada kepentingan dan kesejahteraan orang banyak (masyarakat), sehingga menonjolkan nilai sosial/kemasyarakatan.", 
        hint: "Fokuslah pada dampak tindakan tokoh terhadap masyarakat luas." 
    },

    { id: 99, text: "Penulisan kata depan yang benar dalam kalimat berikut adalah...", options: ["Di rumahnya ada banyak buku.", "Dimana kamu tinggal?", "Di perkirakan akan terjadi hujan.", "Dia dihormati oleh semua orang."], correctAnswer: 0, rationale: "Kata 'di' yang berfungsi sebagai kata depan (menunjukkan tempat) harus dipisah. 'Di' pada 'dimana' (seharusnya 'di mana') dan 'diperkirakan' (seharusnya 'diperkirakan', imbuhan) salah.", hint: "Ingat, 'di' sebagai penunjuk tempat dipisah, 'di' sebagai imbuhan digabung." },
    { id: 100, text: "Unsur intrinsik hikayat yang mencakup tempat, waktu, dan suasana adalah...", options: ["Tema", "Alur", "Latar", "Tokoh"], correctAnswer: 2, rationale: "Latar (setting) meliputi tempat, waktu, dan suasana kejadian dalam cerita.", hint: "Unsur yang menjelaskan di mana dan kapan cerita terjadi." },
    { id: 101, text: "Manakah penulisan daftar pustaka dari sumber internet yang benar?", options: ["Purnama, A. (2023). Teks Laporan Hasil Observasi. Diakses dari www.kompas.com.", "Purnama, A. 2023. Teks Laporan Hasil Observasi. Kompas.com. (Diakses 10 November 2023).", "Purnama, A. (2023). 'Teks Laporan Hasil Observasi'. *Kompas.com*. Dilihat pada 10 November 2023.", "Purnama, A. (2023). Teks Laporan Hasil Observasi. *Kompas.com*. Diakses 10 November 2023, dari https://www.kompas.com."], correctAnswer: 3, rationale: "Penulisan sumber daring harus mencakup Nama (dibalik), (Tahun). Judul Artikel (tidak miring). *Nama Situs* (miring). Tanggal akses, dari URL.", hint: "Perhatikan format Nama Penulis, Tahun, Judul, Situs (miring), dan Tanggal Akses." },
    { id: 102, text: "Kalimat yang menggunakan 'di' sebagai imbuhan (verba pasif) yang benar adalah...", options: ["Makanan itu di masak oleh ibu.", "Surat itu diantar oleh kurir.", "Dia di puji karena prestasinya.", "Sepeda di letakkan di teras."], correctAnswer: 1, rationale: "'Diantar' adalah kata kerja pasif dan penulisannya harus digabung. Opsi lainnya salah penulisan karena 'di' dipisah.", hint: "Imbuhan 'di-' harus selalu digabung dengan kata kerja dasarnya." },
    { id: 103, text: "Majas yang membandingkan benda mati atau abstrak seolah hidup dan memiliki sifat manusia adalah...", options: ["Metafora", "Litotes", "Personifikasi", "Sarkasme"], correctAnswer: 2, rationale: "Personifikasi memberikan sifat manusia pada benda mati (contoh: *Pena menari-nari* di atas kertas).", hint: "Cari majas yang membuat benda mati menjadi 'bernyawa'." },
    { id: 104, text: "Dalam daftar pustaka, penulisan tahun terbit untuk buku terletak...", options: ["Setelah judul buku.", "Sebelum nama penerbit.", "Setelah nama penulis dan diapit tanda kurung.", "Setelah kota terbit."], correctAnswer: 2, rationale: "Aturan umum: Nama (dibalik). (Tahun). Judul. Kota: Penerbit.", hint: "Tahun terletak paling awal setelah nama penulis." },
    { id: 105, text: "Jika terdapat dua penulis, penulisan nama penulis pada daftar pustaka yang benar adalah...", options: ["Nama penulis pertama (dibalik), dan Nama penulis kedua (biasa).", "Kedua nama penulis dibalik semua.", "Hanya nama penulis pertama yang dibalik, diikuti 'dan'.", "Nama penulis pertama dan kedua ditulis biasa."], correctAnswer: 0, rationale: "Hanya nama penulis pertama yang dibalik, sedangkan nama penulis kedua ditulis secara normal.", hint: "Cek nama penulis pertama: Sari, Siska; Penulis kedua: dan Budi Utomo." },
    { id: 106, text: "Manakah penulisan kata 'ke' sebagai kata depan yang salah?", options: ["ke pantai", "ke pasar", "kemari", "kehadiran"], correctAnswer: 2, rationale: "'Kemari' adalah pengecualian yang penulisannya digabung. Kata depan 'ke' harus dipisah. 'Kehadiran' adalah kata benda dengan imbuhan 'ke-an'.", hint: "Kata 'kemari' berarti 'ke sini' dan digabung." },
    { id: 107, text: "Perubahan kata 'serta' menjadi 'menyertai' menggunakan proses afiksasi...", options: ["Prefix meN- dan Suffix -i.", "Prefix meN-.", "Suffix -i.", "Prefix me-."], correctAnswer: 0, rationale: "Kata 'menyertai' memiliki imbuhan awalan *meN-* dan akhiran *-i* (konfiks/gabungan imbuhan).", hint: "Kata 'menyertai' = meN- + serta + -i." },

    // --- Soal ID 108 (EDITED: Rationale disesuaikan) ---
    { id: 108, text: "Majas yang digunakan dalam kalimat 'Pencetak gol terbanyak dari tim ini absen karena cedera?' adalah...",
        options: [
            "Personifikasi",
            "Metafora",
            "Simile",
            "Antonomasia"
        ],
        correctAnswer: 3,
        rationale: "Antonomasia adalah majas yang menyebut seseorang berdasarkan ciri atau sifat atau julukan yang menonjol dan melekat padanya ('Pencetak gol terbanyak' menggantikan nama pemain yang menjadi julukannya).", // Rationale disesuaikan
        hint: "Majas ini mengganti nama orang dengan julukan atau sifat khas yang melekat pada orang tersebut."
    },

    { id: 109, text: "Manakah pernyataan berikut yang paling tepat membedakan Majas Antonomasia dan Personifikasi?",
        options: [
            "Antonomasia mengganti nama orang dengan julukan/sifat menonjol, sedangkan Personifikasi memberikan sifat manusia kepada benda mati.",
            "Antonomasia menggunakan perbandingan eksplisit (seperti, bagai), sedangkan Personifikasi menggunakan perbandingan implisit (langsung).",
            "Antonomasia melebih-lebihkan suatu hal, sedangkan Personifikasi merendahkan suatu hal.",
            "Antonomasia adalah majas perulangan, sedangkan Personifikasi adalah majas pertentangan."
        ],
        correctAnswer: 0,
        rationale: "Perbedaan utamanya adalah objek: Antonomasia berfokus pada orang dan julukan/sifat, sementara Personifikasi berfokus pada benda mati yang diberi sifat manusia.",
        hint: "Kunci perbedaannya ada pada objek yang disasar: orang (Antonomasia) atau benda mati (Personifikasi)."
    },

    // --- SOAL BARU DITAMBAHKAN (ID 110-113) ---

    // Soal Baru 1 (ID 110) - Kisi-kisi 19: Kata Arkais
    { id: 110, text: "Bacalah kutipan hikayat berikut:\n*Maka* si miskin pun sampailah ke negeri Antah Berantah. *Hatta*, ia memohon kepada *baginda* raja untuk diizinkan tinggal di sana. Beberapa tahun kemudian, si miskin berubah menjadi kaya raya.",
        options: [
            "'si miskin' dan 'kaya raya'",
            "'Maka' dan 'beberapa tahun'",
            "'Hatta' dan 'baginda'",
            "'negeri Antah Berantah' dan 'raja'"
        ],
        correctAnswer: 2,
        rationale: "Kata arkais adalah kata kuno yang tidak lazim digunakan dalam bahasa modern. 'Hatta' (kemudian) dan 'baginda' (sebutan untuk raja) adalah contoh kata arkais yang sering muncul dalam hikayat.",
        hint: "Fokus pada kata-kata yang jarang digunakan dalam percakapan sehari-hari saat ini."
    },

    // Soal Baru 2 (ID 111) - Kisi-kisi 23: Alur Berbingkai
    { id: 111, text: "Dalam struktur cerita hikayat, sering ditemukan cerita utama yang di dalamnya terdapat cerita lain yang dituturkan oleh tokoh utama atau tokoh sampingan. Struktur penceritaan ini disebut...",
        options: [
            "Istanasentris",
            "Alur maju",
            "Alur berbingkai",
            "Kemustahilan"
        ],
        correctAnswer: 2,
        rationale: "Alur berbingkai (*nested plot* atau cerita di dalam cerita) adalah ciri khas hikayat di mana narator membingkai cerita utama dengan cerita lain yang saling terkait.",
        hint: "Istilah ini mengacu pada bingkai cerita yang membungkus cerita lain di dalamnya."
    },

    // Soal Baru 3 (ID 112) - Kisi-kisi 14: Perbedaan Teks Humor dan Teks Anekdot
    { id: 112, text: "Pernyataan yang paling tepat menunjukkan perbedaan antara Teks Humor dan Teks Anekdot adalah...",
        options: [
            "Anekdot bertujuan menghibur dan harus berbasis fakta, sementara Humor bertujuan menghibur dan boleh fiksi.",
            "Anekdot selalu memiliki tokoh binatang, sementara Humor selalu memiliki tokoh manusia.",
            "Anekdot menyindir tokoh penting/kebijakan publik, sementara Humor hanya bertujuan menghibur tanpa ada sindiran.",
            "Anekdot memiliki krisis dan reaksi, sementara Humor hanya memiliki abstraksi dan koda."
        ],
        correctAnswer: 2,
        rationale: "Perbedaan utama: Anekdot memiliki fungsi menyindir atau mengkritik (umumnya tokoh penting/kebijakan), sedangkan Humor murni untuk melucu/menghibur tanpa maksud sindiran tersembunyi.",
        hint: "Fungsi utama Anekdot adalah kritik, bukan hanya menghibur."
    },

    // Soal Baru 4 (ID 113) - Kisi-kisi 5: Kaidah Kebahasaan Teks LHO (Nomina/Verba)
    { id: 113, text: "Perhatikan kalimat dari LHO berikut: 'Harimau **termasuk** hewan yang **dilindungi** karena populasinya terus **berkurang**.' Manakah yang merupakan contoh Nomina (Kata Benda) dalam kalimat tersebut?",
        options: [
            "termasuk",
            "dilindungi",
            "populasinya",
            "berkurang"
        ],
        correctAnswer: 2,
        rationale: "Nomina (Kata Benda) adalah kata yang mengacu pada benda, nama, atau konsep. 'Populasinya' (Populasi) adalah kata benda. 'Termasuk', 'dilindungi', dan 'berkurang' adalah Verba (Kata Kerja).",
        hint: "Nomina dapat didahului oleh kata sandang 'si' atau 'sang' atau diiringi oleh sufiks posesif seperti '-nya'."
    }
];
